# Installation and setup
- name: Make sure zsh is installed
  apt: name=zsh state=present
  become: true
  when: ansible_os_family == "Debian"

- name: ensure zsh is default shell
  become: true
  shell: chsh -s $(which zsh)
  when: ansible_os_family == "Debian"

- name: Change user shell to zsh 
  become: true
  user:
    name: "ratingminus"
    shell: /bin/zsh
  when: ansible_os_family == "Debian"

# Configuration
- name: Check if zshrc already exists
  stat: path="{{user_home}}/.zshrc"
  register: zshrc_stat

- name: Back up zshrc if it exists
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{user_home}}/.zshrc.bak"
  when: zshrc_stat.stat.exists

# Oh-my-zsh
- import_tasks: oh-my-zsh.yml
  # powerlevel10k
- import_tasks: p10k.yml