- name: Install Oh My Zsh # noqa: latest
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{user_home}}/.oh-my-zsh"
    depth: 1
 
- name: Install zsh-autosuggestions plugin # noqa: latest
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{user_home}}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: 1
 
- name: Install zsh-completions plugin # noqa: latest
  git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: "{{user_home}}/.oh-my-zsh/custom/plugins/zsh-completions"
    depth: 1
 
- name: Install zsh-syntax-highlighting plugin # noqa: latest
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{user_home}}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    depth: 1

- name: Generate zshrc
  copy:
    src: "{{user_home}}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "{{user_home}}/.zshrc"
    mode: 0644

- name: Activate plugins
  lineinfile:
    path: "{{user_home}}/.zshrc"
    regexp: "^plugins="
    line: "plugins=(
            git 
            zsh-autosuggestions 
            zsh-completions 
            zsh-syntax-highlighting 
            ohmyzsh-full-autoupdate
            )"