- name: install and configure ohmyzsh
  import_role:
    name: gantsign.oh-my-zsh
  vars:
    users:
      - username: "{{shell_user}}"
        oh_my_zsh:
          theme: powerlevel10k/powerlevel10k
          plugins:
            - git
            - zsh-autosuggestions 
            - zsh-syntax-highlighting
            - ohmyzsh-full-autoupdate
          update_mode: auto
          write_zshrc: true