- name: Update APT Mirror
  become: true
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    backup: yes
  register: replace_ubuntu_apt_config

- name: update apt cache on ubuntu
  become: true
  apt:
    update_cache: yes
  when: replace_ubuntu_apt_config.changed