- name: Update APT Mirror
  block:

    - name: replace apt mirror on ubuntu
      become: true
      template:
        src: templates/sources.list.j2
        dest: /etc/apt/sources.list
        backup: yes
      register: replace_ubuntu_apt_config

    - name: update apt cache on ubuntu
      become: true
      apt:
        update_cache: yes
      when: replace_ubuntu_apt_config.changed