- name: Install git with apt
  apt: name=git state=present
  become: true
  when: ansible_os_family == "Debian"

- name: Make sure gitconfig is up to date
  template:
    src: gitconfig.j2
    dest: "{{user_home}}/.gitconfig"
    backup: true